#!/bin/bash
##
#   Script to set the position of a moveable Conky
#
#   Written by damo <damo@bunsenlabs.org> November 2015
#   with major contributions of functions, commands and suggestions by @johnraff

DIALOG="yad --center --undecorated --borders=20 \
--window-icon=/usr/share/pixmaps/Bunsenlabs-flame-256.svg"

unset CONKYPATH posX_1 posY_1 posX_2 posY_2 OFFSET_X OFFSET_Y gapX gapY

# makes array "config"
function parse_conkyfile(){   # function by @johnraff
    [[ -f $1 ]] || { echo "$1 is not a file." >&2;return 1;}
    unset config
    declare -Ag config
    local name value
    while read name value
    do
        [[ $name ]] || continue
        [[ $name = TEXT* ]] && break
        config["$name"]="$value"
    done < <(sed 's/\#.*$//' "$1")
}

# usage: edit_conkyfile file name=value [name2=value2...]
# use absolute path to file
function edit_conkyfile(){   # function by @johnraff
    [[ $1 = /* ]] || {
        echo "$0: $1 is not an absolute path." >&2
        return 1
    }
    file=$1
    shift
    parse_conkyfile "$file"
    local name value
    unset sed_cmd
    while [[ $1 ]]; do
        unset name value sed_pattern sed_replace
        name="${1%%=*}"
        value="${1#*=}"
        shift
        [[ ${config["$name"]+x} ]] || {
            echo "$0: config key $name does not exist" >&2
            return 1
        }
        [[ ${config["$name"]//[[:space:]]} = "${value//[[:space:]]}" ]] && continue
        sed_pattern="^ *$name .*$"
        grep -q "#conkymove, original $name:" "$file" || sed_replace="#conkymove, original $name: ${config[$name]}\n"
        sed_replace+="$name $value"
        sed_cmd+="s/$sed_pattern/$sed_replace/;"
    done
    [[ "$sed_cmd" ]] && {
        sed -ri "$sed_cmd" "$file"
    }
}

function getStart(){    #   Get initial Conky position
    unset CONKYPATH
    while read CLICKED;do
        ID=$(grep "Window id:" | awk '{print $4}') <<< $CLICKED
    done < <(xwininfo)
    
    # command suggested by @johnraff....
    CMD=$(xprop -id $ID  WM_COMMAND | awk -F '", "' '{cmd=$1;sub(/^.*{ "/,"",cmd);for (i=1;i<=NF;i++)if($i=="-c"){i++;sub(/\" }$/,"",$i);gsub(/\\\"/,"\"",$i);print cmd,$i;exit}}')

    if grep "conky" <<< $CMD &>/dev/null;then
        echo "Found a conky"
        CONKYPATH=${CMD##* }
        WINX_1=$(xwininfo -int -id $ID  | grep "Absolute upper-left X")
        posX_1=${WINX_1##* }
        WINY_1=$(xwininfo -int -id $ID  | grep "Absolute upper-left Y")
        posY_1=${WINY_1##* }
    else
        echo "Selection is not a conky"
        $DIALOG --button="OK:0" --text="Selection is not a conky\n\nChoose again"
        getStart
    fi
}

function getFinish(){   #   Get new Conky position
    WINX_2=$(xwininfo -int -id $ID  | grep "Absolute upper-left X")
    posX_2=${WINX_2##* }
    WINY_2=$(xwininfo -int -id $ID  | grep "Absolute upper-left Y")
    posY_2=${WINY_2##* }
}

function getOffset(){
    unset VAR VAL
    while read VAR VAL;do
        case $VAR in
            alignment)  align="$VAL";;
            gap_x    )  gapX=$VAL;;
            gap_y    )  gapY=$VAL;;
        esac
    done < <(cat $CONKYPATH)

    OFFSET_X=$(( posX_2 - posX_1 ))
    OFFSET_Y=$(( posY_2 - posY_1 ))

    case $align in 
        tr|top_right|mr|middle_right|br|bottom_right|mm|middle_middle|bm|bottom_middle|tm|top_middle)
            gapX=$(( gapX - OFFSET_X ))
            ;;
        tl|top_left|ml|middle_left|bl|bottom_left)
            gapX=$(( gapX + OFFSET_X ))
            ;;
    esac
    case $align in
        tr|top_right|tl|top_left|tm|top_middle)
            gapY=$(( gapY + OFFSET_Y ))
            ;;
        br|bottom_right|bl|bottom_left|bm|bottom_middle|mm|middle_middle|ml|middle_left|mr|middle_right)
            gapY=$(( gapY - OFFSET_Y ))
            ;;
    esac
    if [[ $align = none ]];then   # placement managed by Openbox
        TXT="This Conky has 'alignment none'\nso placement is handled by the Window Manager.\n"
        $DIALOG --text="$TXT" --button="OK"
        echo -e "\nConky has 'alignment none',\nso placement is handled by the Window Manager\nExiting...\n"
        exit 0
    fi
}

$DIALOG --text="Click OK to pick a conky\nand record the conky position" \
     --button="Select Conky:0" --button="gtk-cancel:1"

if (( $? == 0 ));then
    getStart
else
    echo "  Cancelled: exiting..."
    exit 0
fi

$DIALOG --text="Move the Conky to the desired location\nthen click 'OK'" \
     --button="OK:0" --button="gtk-cancel:1"

if (( $? == 0 ));then
    getFinish
else
    echo "  Cancelled: exiting..."
    exit 0
fi

getOffset

edit_conkyfile "$CONKYPATH" "gap_x"=$gapX "gap_y"=$gapY

exit 0
