#!/bin/bash
##
# bl-script will make a new script in ~/bin, make it executable,
# then open it in the default text editor.
#
# The script name can be entered as a script parameter, or if none is given
# it can be entered in an entry dialog
#
# Written by <damo> for BunsenLabs Linux, February 2016 
#
########################################################################

BIN="$HOME/bin"

if (( $# == 0 ));then
    while :; do
        NAME=$(yad --entry --title="New script" \
                --window-icon="distributor-logo-bunsenlabs" \
                --center --text="Enter script name..." --width=400 \
                )
        RET=$?
        if (( $RET == 1 ));then
            exit
        fi
        if ! [[ -z $NAME ]];then
            if [ -f "$BIN/$NAME" ];then
                yad --title="New script" --text="File exists. Overwrite?" \
                --window-icon="distributor-logo-bunsenlabs" \
                --image="dialog-question" \
                --center --undecorated \
                
                if (( $? == 0 ));then
                    break
                else
                    echo "Cancelled overwrite..."
                fi
            else
                break
            fi
        fi
    done
else
    NAME=$1
    if [ -f "$BIN/$NAME" ];then
        yad --title="New script" --text="File exists. Overwrite?" \
            --window-icon="distributor-logo-bunsenlabs" \
            --image="dialog-question" \
            --center --undecorated

        if (( $? == 1 ));then
            exit
        fi
    fi
fi

FPATH="$BIN/$NAME"

if type bl-text-editor &>/dev/null;then 
    EDITOR=$(readlink -f $(which bl-text-editor))
else
    EDITOR=xdg-open
fi

> "$FPATH"
echo "#!/bin/bash" > "$FPATH"
echo -e "##\n## $NAME\n" >> "$FPATH"

chmod +x "$FPATH"

if [[ $EDITOR = "/usr/bin/geany" ]];then
    $EDITOR "$FPATH:5:1" &  # set cursor at last line
else
    $EDITOR "$FPATH" &
fi

exit 0
