#!/bin/bash
##
# bl-script will make a new script in ~/bin, make it executable,
# then open it in the default text editor.
#
# Written by <damo> for BunsenLabs

BIN="$HOME/bin"

if [ $# -lt 1 ];then
    LOOP=1
    while [[ $LOOP == 1 ]];do
        NAME=$(zenity --entry --title="New script" \
            --text="Enter script name..." --width=400)
        RET=$?
        if [[ $RET = 1 ]];then
            exit
        fi
        if ! [[ -z $NAME ]];then
            if [ -f "$BIN/$NAME" ];then
                zenity --question --title="New script" --text="File exists. Overwrite?"
                if [[ $? = 0 ]];then
                    break
                else
                    echo "Cancelled overwrite..."
                fi
            else
                break
            fi
        fi
    done
else
    NAME=$1
    if [ -f "$BIN/$NAME" ];then
        zenity --question --title="New script" --text="File exists. Overwrite?"
        if [[ $? = 1 ]];then
            exit
        fi
    fi
fi

FPATH="$BIN/$NAME"

if type bl-text-editor &>/dev/null;then 
    EDITOR=$(readlink -f $(which bl-text-editor))
else
    EDITOR=xdg-open
fi

> "$FPATH"
echo "#!/bin/bash" > "$FPATH"
echo -e "##\n## $NAME\n" >> "$FPATH"

chmod +x "$FPATH"

if [[ $EDITOR = "/usr/bin/geany" ]];then
    $EDITOR "$FPATH:5:1" &  # set cursor at last line
else
    $EDITOR "$FPATH" &
fi

exit 0
