#!/bin/bash
##
## Use yad dialogs to record sound stream, and edit saved sound file
##
## written by <damo> June 2015

SRC="alsa_output.pci-0000_00_1b.0.analog-stereo.monitor"
SOUNDEDIT="/usr/bin/mhwaveedit"

RECORD=$(yad --file --save \
--title="Record stream" --height=600 --width=600 --center \
--button=Save:0 --button=gtk-cancel:1 \
)
RET=$?
RECORD="$RECORD.mp3" # add mp3 filetype

if [[ $RET = 0 ]];then
    if [ -f "$RECORD" ];then
        FYAD=$(yad --form --text="Overwrite?" --center)
        if [[ $? = 0 ]];then
            rm "$RECORD"    # avconv won't auto-overwrite, so delete existing file
        else
            echo "Cancelled overwrite..."
            exit
        fi
    fi
else
    echo "Cancelled"
    exit
fi

avconv -f pulse -i $SRC "$RECORD" &

# progress bar
running=1
while [[ $running ]];do
    echo ""
    sleep 1s
done | \
yad --progress --pulsate --text="Stop recording?" --button=Stop:0 --center

killall avconv
$SOUNDEDIT "$RECORD" &      # run sound editor

exit 0
