#!/bin/bash
##
## Record soundcard output (using pulse); then open file for editing
#
# <damo> February 2016
#
########################################################################

SOUNDEDITOR="/usr/bin/mhwaveedit --driver pulse"
FTYPE="mp3"

# get pulseaudio soundcard output name
SRC=$(pacmd list-sources | grep analog | awk '/name:.+\.monitor/' | awk '$0=$2' FS='<' RS='>')

while : ;do
    RECORD=$(yad --file --save \
    --title="Record stream" --height=600 --width=600 --center \
    --window-icon=distributor-logo-bunsenlabs \
    --button=Save:0 --button=gtk-cancel:1 \
    )
    RET=$?
    RECORDING="$RECORD.$FTYPE" # add file extension
    if [[ $RET = 0 ]];then
        if ! [[ -z $RECORD ]];then
            if [ -f "$RECORDING" ];then
                DLG=$(yad --form --text="File exists. Overwrite?" \
                --title="Record stream" --center --undecorated \
                --window-icon=distributor-logo-bunsenlabs \
                )
                if [[ $? = 0 ]];then
                    rm "$RECORDING"    # ffmpeg won't auto-overwrite, so delete existing file
                    break
                else
                    echo "Cancelled overwrite..."
                fi
            else
                break
            fi
        else    # loop if no filename entered
            DLG=$(yad --form --text="Enter a filename" \
            --window-icon=distributor-logo-bunsenlabs \
            --title="Record stream" --center --undecorated --button=OK:0 \
            --width=300 \
            )
        fi
    else
        echo "Cancelled"
        exit
    fi
done

REC=$(yad --form --text="Start recording $RECORDING?" --title="Record stream" \
    --window-icon=distributor-logo-bunsenlabs \
    --center --button=OK:0 --button=Exit:1 \
    --width=300 \
    )
if (( $? == 0 ));then
    ffmpeg -f pulse -ac 2 -i $SRC "$RECORDING" &
else
    exit
fi
    
# progress bar
while : ; do
    echo ""
    sleep 1s
    done | \
    DLG=$(yad --progress --pulsate --text="Stop recording?" \
    --title="Record stream" --button=Stop:0 --center \
    --window-icon=distributor-logo-bunsenlabs \
    --width=300 \
    )
    
if (( $? == 0 ));then
    killall ffmpeg
else
    exit 0
fi

echo -e "Starting sound editor...\n"
$SOUNDEDITOR "$RECORDING" &      # run sound editor

exit 0
