#!/bin/bash
##

SOUNDEDITOR="/usr/bin/mhwaveedit"
FTYPE="mp3"

# get pulseaudio soundcard output name
SRC=$(pacmd list-sources | awk '/name:.+\.monitor/' | awk '$0=$2' FS='<' RS='>')

LOOP=1
while [[ $LOOP = 1 ]];do
    RECORD=$(yad --file --save \
    --title="Record stream" --height=600 --width=600 --center \
    --button=Save:0 --button=gtk-cancel:1 \
    )
    RET=$?
    echo "RET= $RET"

    RECORD="$RECORD.$FTYPE" # add file extension
    echo "REC= $RECORD"
    if [[ $RET = 0 ]];then
        if [ -f "$RECORD" ];then
            FYAD=$(yad --form --text="File exists. Overwrite?" --center)
            if [[ $? = 0 ]];then
                rm "$RECORD"    # avconv won't auto-overwrite, so delete existing file
                break
            else
                echo "Cancelled overwrite..."
            fi
        else
            break
        fi
    else
        echo "Cancelled"
        exit
    fi
done

avconv -f pulse -i $SRC "$RECORD" &

# progress bar
running=1
while [[ $running ]];do
    echo ""
    sleep 1s
done | \
yad --progress --pulsate --text="Stop recording?" --button=Stop:0 --center

killall avconv
$SOUNDEDITOR "$RECORD" &      # run sound editor

exit 0
