#!/bin/bash
##
## record-zen: version using zenity dialog

SOUNDEDITOR="/usr/bin/audacity"
FTYPE="mp3"

# get pulseaudio soundcard output name
SRC=$(pacmd list-sources | awk '/name:.+\.monitor/' | awk '$0=$2' FS='<' RS='>')

LOOP=1
while [[ $LOOP = 1 ]];do
    RECORD=$(zenity --file-selection --save \
    --title="Record stream" --height=600 --width=600 \
    )
    RET=$?
    echo "RET= $RET"

    RECORD="$RECORD.$FTYPE" # add file extension
    echo "REC= $RECORD"
    if [[ $RET = 0 ]];then
        if [ -f "$RECORD" ];then
            FZEN=$(zenity --question --text="File exists. Overwrite?" )
            if [[ $? = 0 ]];then
                rm "$RECORD"    # avconv won't auto-overwrite, so delete existing file
                break
            else
                echo "Cancelled overwrite..."
            fi
        else
            break
        fi
    else
        echo "Cancelled"
        exit
    fi
done

avconv -f pulse -i $SRC "$RECORD" &

# progress bar
running=1
while [[ $running ]];do
    echo ""
    sleep 1s
done | \
zenity --question --text="Stop recording?" 

killall avconv
$SOUNDEDITOR "$RECORD" &      # run sound editor

exit 0
