#!/bin/bash
##
#
#	USAGE	"utube outputfile url"

COMMAND="youtube-dl -o "

if [ $# -lt 2 ]; then
    echo 'Use utube <output filepath> <"url">'
    exit
fi

OUTPUT="$1"
LINK="$2"

$COMMAND $OUTPUT $LINK
exit
