#! /bin/bash
#
# Super simple logout/shudown/reconfigure yad dialog
# by <damo> October 2014
#
# If you don't have yad you can get it from http://sourceforge.net/projects/yad-dialog/
# Or get a deb package from http://pkgs.org/download/yad and install with dpkg -i
#
#----------------------------------------------------------------
# INIT USERS: add yourself to sudoers for shutdown/reboot
# So edit sudoers with "sudo visudo", and add
#
#  ALL   ALL=NOPASSWD:/sbin/reboot
#  ALL   ALL=NOPASSWD:/sbin/poweroff
#----------------------------------------------------------------
#  SYSTEMD USERS: "polkit is necessary for power management as an 
# unprivileged user. If you are in a local systemd-logind user session
# and no other session is active, the following commands will work
# without root privileges. If not (for example, because another user
# is logged into a tty), systemd will automatically ask you for the
# root password"
#
# If you aren't using polkit then add yourself to sudoers for shutdown/halt/reboot
# Edit sudoers with "sudo visudo", and add
#
# ALL   ALL=NOPASSWD: /usr/bin/systemctl poweroff,/usr/bin/systemctl halt,/usr/bin/systemctl reboot
#----------------------------------------------------------------

# See if yad dialog is installed
TESTYAD=`which yad`
TEXT="You need to install YAD dialog.\nIt is available from http://sourceforge.net/projects/yad-dialog.\nCompile from source, or download a deb package and use dpkg -i"

if [ "$TESTYAD" = "" ];then
    zenity --warning --text="$TEXT"
    exit 0
fi

dialog=$(yad --undecorated --center --on-top\
    --text="  Shutdown ${USER}'s System?"\
    --text-align=center\
    --button="gtk-cancel:1" \
    --button="Power Off":2 \
    --button="Reboot":3 \
    --button="Logout":4 \
    --button="Suspend":5 \
    --button="Reconfig":6 \
    )
ret=$?

# Comment/Uncomment the case stanza depending if you use init/systemd

#case $ret in
    #1) exit 0;;
    #2) cmd="sudo /sbin/poweroff";;
    #3) cmd="sudo /sbin/reboot" ;;
    #4) cmd="openbox --exit";;
    #5) cmd="dbus-send --system --print-reply --dest=\"org.freedesktop.UPower\" /org/freedesktop/UPower org.freedesktop.UPower.Suspend";;
    #6) cmd="openbox --reconfigure";;
    #*) exit 1;;
#esac

case $ret in
    1) exit 0;;
    2) cmd="systemctl poweroff";;
    3) cmd="systemctl reboot" ;;
    4) cmd="openbox --exit";;
    5) cmd="systemctl suspend";;
    6) cmd="openbox --reconfigure";;
    *) exit 1;;
esac


eval exec $cmd
