#!/bin/bash
##
## yad dialog to download and save youtube video
##
## written by <damo> June 2015, updated May 2016

CMD="youtube-dl --ignore-errors --output "
FTYPES="mp4!avi!mov!wmv!flv!3gp!mkv"

if ! type youtube-dl &>/dev/null;then
    DLG=$(yad --form --window-icon=distributor-logo-bunsenlabs \
        --borders=10 \
        --text="   youtube-dl not found\n\n  Install it first and run the script again" --button="OK" \
        --title="Youtube downloader" --center --undecorated \
    )
    exit
fi

while :; do
    ENTRY=$(yad --form --window-icon=distributor-logo-bunsenlabs --center \
        --borders=10 \
        --title="Youtube downloader" \
        --field="Enter Filename (without extension)":SFL \
        --field="Enter youtube url" \
        --field="Filetype:CB" \
        "" "" "$FTYPES" \
        )
    RET=$?

    OIFS=$IFS # save Internal Field Separator
    IFS="|" # separator is "|" in returned choices
    i=0
    retChoice=()

    for ret in $ENTRY;do 
        retChoice[$i]="$ret"
        i=$(($i+1))
    done

    IFS=$OIFS # reset IFS back to default

    SAVE=${retChoice[0]}
    URL=${retChoice[1]}
    URL=${URL##*'='}
    FTYPE=${retChoice[2]}

    if (( $RET == 1 ));then
        exit
    fi
    if [[ -z $SAVE ]] || [[ -z $URL ]] || [[ -z $FTYPES ]];then
        yad --form --text="Complete both fields" --center --window-icon=distributor-logo-bunsenlabs
    else
        break
    fi
done

RECORDING="$SAVE.$FTYPE" # add file extension

if (( $RET == 0 ));then
    while :; do
        if [[ -f $RECORDING ]];then
            DLG=$(yad --form --window-icon=distributor-logo-bunsenlabs \
                --borders=10 \
                --text="File exists. Overwrite?" \
                --title="Youtube downloader" --center --undecorated \
                )
            if (( $? == 1 ));then
                echo "Cancelled overwrite..."
                exit
            else
                rm "$RECORDING"
                break
            fi
        else
            break
        fi
    done
fi

# Run youtube download, pipe to progress dialog
$CMD $RECORDING $URL | yad --borders=10 --progress --pulsate --progress-text="Downloading..." \
            --auto-kill --auto-close \
            --window-icon=distributor-logo-bunsenlabs \
            --center --undecorated --text="Youtube downloader: \n" 

# Remove part file if download was cancelled or interrupted
if [[ -f "$RECORDING.part" ]];then
    rm "$RECORDING.part"
    exit
fi
            
xdg-open "$RECORDING"

exit 0

